#PBS -l select=18:ncpus=36:mpiprocs=36
#PBS -N Test
#PBS -A UPSU0040
#PBS -l walltime=01:00:00
#PBS -j oe
#PBS -q economy

cd $PBS_O_WORKDIR
cd ../run

echo " "
echo " "
echo "Job started on `hostname` at `date`"
export TMPDIR=/glade/scratch/$USER/temp
mkdir -p $TMPDIR

module load ncarenv/1.3
#module load gnu/8.3.0 
module load netcdf/4.7.4
module load R/3.6.0 
module load ncarcompilers/0.5.0
module load openmpi/3.1.4

mpirun -n 1 Rscript B_run_mpi.R
echo "Job ended on `hostname` at `date`"
